document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'UTF-8\'>");
document.writeln("		<title></title>");
document.writeln("");
document.writeln("		");
document.writeln("		<style type=\'text/css\'>");
document.writeln("			body{");
document.writeln("				display: block;");
document.writeln("			}");
document.writeln("			#container{");
document.writeln("				width: 1080px;");
document.writeln("				margin: 0 auto;");
document.writeln("			}");
document.writeln("		</style>");
document.writeln("			");
document.writeln("		</style>");
document.writeln("");
document.writeln("		");
document.writeln("		<link rel=\'stylesheet\' href=\'css/menubar.css\' type=\'text/css\' media=\'screen\' />");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<div id=\'container\'>");
document.writeln("			<div id=\'head\' align=\'left\'>");
document.writeln("				<div >	<img src=\'img/logo.png\' /></div>				");
document.writeln("			</div>");
document.writeln("			<div id=\'menubar\'>     ");
document.writeln("           <ul>     ");
document.writeln("               <li class=\'first\'>      ");
document.writeln("                   <a href=\'#\'>Information<a>     ");
document.writeln("                   <ul>     ");
document.writeln("                       <li>     ");
document.writeln("                           <a href=\'#\'>Student</a>     ");
document.writeln("                       </li>     ");
document.writeln("                       <li>     ");
document.writeln("                           <a href=\'#\'>Parent</a>     ");
document.writeln("                       </li>     ");
document.writeln("                   </ul>     ");
document.writeln("               </li>     ");
document.writeln("               <li>      ");
document.writeln("                   <a href=\'#\'>Payment<a>");
document.writeln("               </li>     ");
document.writeln("               <li>      ");
document.writeln("                   <a href=\'#\'>Rank<a>     ");
document.writeln("               </li>     ");
document.writeln("               <li>      ");
document.writeln("                   <a href=\'#\'>Class<a>     ");
document.writeln("               </li>  ");
document.writeln("               ");
document.writeln("               ");
document.writeln("           </ul>     ");
document.writeln("       ");
document.writeln("			</div>");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");