package com.group12.domain.entity;
// Generated 2017-3-30 17:33:33 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttainId generated by hbm2java
 */
@Embeddable
public class AttainId implements java.io.Serializable {

	private int rankNum;
	private int stuNum;
	private int invNum;

	public AttainId() {
	}

	public AttainId(int rankNum, int stuNum, int invNum) {
		this.rankNum = rankNum;
		this.stuNum = stuNum;
		this.invNum = invNum;
	}

	@Column(name = "Rank_Num", nullable = false)
	public int getRankNum() {
		return this.rankNum;
	}

	public void setRankNum(int rankNum) {
		this.rankNum = rankNum;
	}

	@Column(name = "Stu_Num", nullable = false)
	public int getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(int stuNum) {
		this.stuNum = stuNum;
	}

	@Column(name = "Inv_Num", nullable = false)
	public int getInvNum() {
		return this.invNum;
	}

	public void setInvNum(int invNum) {
		this.invNum = invNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttainId))
			return false;
		AttainId castOther = (AttainId) other;

		return (this.getRankNum() == castOther.getRankNum()) && (this.getStuNum() == castOther.getStuNum())
				&& (this.getInvNum() == castOther.getInvNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRankNum();
		result = 37 * result + this.getStuNum();
		result = 37 * result + this.getInvNum();
		return result;
	}

}
