package com.group12.domain.entity;
// Generated Apr 9, 2017 5:30:06 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attain generated by hbm2java
 */
@Entity
@Table(name = "attain", catalog = "SKF")
public class Attain implements java.io.Serializable {

	private int invNum;
	private int rankNum;
	private int stuNum;
	private Date rankTestTime;
	private Boolean rankIsPassed;

	public Attain() {
	}

	public Attain(int invNum, int rankNum, int stuNum) {
		this.invNum = invNum;
		this.rankNum = rankNum;
		this.stuNum = stuNum;
	}

	public Attain(int invNum, int rankNum, int stuNum, Date rankTestTime, Boolean rankIsPassed) {
		this.invNum = invNum;
		this.rankNum = rankNum;
		this.stuNum = stuNum;
		this.rankTestTime = rankTestTime;
		this.rankIsPassed = rankIsPassed;
	}

	@Id

	@Column(name = "Inv_Num", unique = true, nullable = false)
	public int getInvNum() {
		return this.invNum;
	}

	public void setInvNum(int invNum) {
		this.invNum = invNum;
	}

	@Column(name = "Rank_Num", nullable = false)
	public int getRankNum() {
		return this.rankNum;
	}

	public void setRankNum(int rankNum) {
		this.rankNum = rankNum;
	}

	@Column(name = "Stu_Num", nullable = false)
	public int getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(int stuNum) {
		this.stuNum = stuNum;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Rank_Test_Time", length = 19)
	public Date getRankTestTime() {
		return this.rankTestTime;
	}

	public void setRankTestTime(Date rankTestTime) {
		this.rankTestTime = rankTestTime;
	}

	@Column(name = "Rank_Is_Passed")
	public Boolean getRankIsPassed() {
		return this.rankIsPassed;
	}

	public void setRankIsPassed(Boolean rankIsPassed) {
		this.rankIsPassed = rankIsPassed;
	}

}
