package com.group12.domain.entity;
// Generated Apr 2, 2017 1:34:23 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendanceId generated by hbm2java
 */
@Embeddable
public class AttendanceId implements java.io.Serializable {

	private int classId;
	private int stuNum;
	private Date attendDate;

	public AttendanceId() {
	}

	public AttendanceId(int classId, int stuNum, Date attendDate) {
		this.classId = classId;
		this.stuNum = stuNum;
		this.attendDate = attendDate;
	}

	@Column(name = "Class_ID", nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Column(name = "Stu_Num", nullable = false)
	public int getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(int stuNum) {
		this.stuNum = stuNum;
	}

	@Column(name = "Attend_Date", nullable = false, length = 10)
	public Date getAttendDate() {
		return this.attendDate;
	}

	public void setAttendDate(Date attendDate) {
		this.attendDate = attendDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttendanceId))
			return false;
		AttendanceId castOther = (AttendanceId) other;

		return (this.getClassId() == castOther.getClassId()) && (this.getStuNum() == castOther.getStuNum())
				&& ((this.getAttendDate() == castOther.getAttendDate())
						|| (this.getAttendDate() != null && castOther.getAttendDate() != null
								&& this.getAttendDate().equals(castOther.getAttendDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClassId();
		result = 37 * result + this.getStuNum();
		result = 37 * result + (getAttendDate() == null ? 0 : this.getAttendDate().hashCode());
		return result;
	}

}
