package com.group12.domain.entity;
// Generated 2017-3-30 17:33:33 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Class generated by hbm2java
 */
@Entity
@Table(name = "class", catalog = "SKF")
public class Class implements java.io.Serializable {

	private Integer classId;
	private String classRoom;
	private String classWeekday;
	private Date classStartTime;
	private Date classEndTime;
	private int classLevel;
	private String classInstructor;

	public Class() {
	}

	public Class(String classRoom, String classWeekday, Date classStartTime, Date classEndTime, int classLevel,
			String classInstructor) {
		this.classRoom = classRoom;
		this.classWeekday = classWeekday;
		this.classStartTime = classStartTime;
		this.classEndTime = classEndTime;
		this.classLevel = classLevel;
		this.classInstructor = classInstructor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Class_ID", unique = true, nullable = false)
	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	@Column(name = "Class_Room", nullable = false, length = 45)
	public String getClassRoom() {
		return this.classRoom;
	}

	public void setClassRoom(String classRoom) {
		this.classRoom = classRoom;
	}

	@Column(name = "Class_Weekday", nullable = false, length = 45)
	public String getClassWeekday() {
		return this.classWeekday;
	}

	public void setClassWeekday(String classWeekday) {
		this.classWeekday = classWeekday;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Class_Start_Time", nullable = false, length = 8)
	public Date getClassStartTime() {
		return this.classStartTime;
	}

	public void setClassStartTime(Date classStartTime) {
		this.classStartTime = classStartTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Class_End_Time", nullable = false, length = 8)
	public Date getClassEndTime() {
		return this.classEndTime;
	}

	public void setClassEndTime(Date classEndTime) {
		this.classEndTime = classEndTime;
	}

	@Column(name = "Class_Level", nullable = false)
	public int getClassLevel() {
		return this.classLevel;
	}

	public void setClassLevel(int classLevel) {
		this.classLevel = classLevel;
	}

	@Column(name = "Class_Instructor", nullable = false, length = 45)
	public String getClassInstructor() {
		return this.classInstructor;
	}

	public void setClassInstructor(String classInstructor) {
		this.classInstructor = classInstructor;
	}

}
