package com.group12.domain.entity;
// Generated 2017-3-30 17:33:33 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membership generated by hbm2java
 */
@Entity
@Table(name = "membership", catalog = "SKF")
public class Membership implements java.io.Serializable {

	private int invNum;
	private int memCode;
	private String memName;
	private String memDescript;
	private Date memStart;
	private Date memEnd;

	public Membership() {
	}

	public Membership(int invNum, int memCode, String memName, String memDescript, Date memStart, Date memEnd) {
		this.invNum = invNum;
		this.memCode = memCode;
		this.memName = memName;
		this.memDescript = memDescript;
		this.memStart = memStart;
		this.memEnd = memEnd;
	}

	@Id

	@Column(name = "Inv_Num", unique = true, nullable = false)
	public int getInvNum() {
		return this.invNum;
	}

	public void setInvNum(int invNum) {
		this.invNum = invNum;
	}

	@Column(name = "Mem_Code", nullable = false)
	public int getMemCode() {
		return this.memCode;
	}

	public void setMemCode(int memCode) {
		this.memCode = memCode;
	}

	@Column(name = "Mem_Name", nullable = false, length = 45)
	public String getMemName() {
		return this.memName;
	}

	public void setMemName(String memName) {
		this.memName = memName;
	}

	@Column(name = "Mem_Descript", nullable = false, length = 45)
	public String getMemDescript() {
		return this.memDescript;
	}

	public void setMemDescript(String memDescript) {
		this.memDescript = memDescript;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Mem_Start", nullable = false, length = 10)
	public Date getMemStart() {
		return this.memStart;
	}

	public void setMemStart(Date memStart) {
		this.memStart = memStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Mem_End", nullable = false, length = 10)
	public Date getMemEnd() {
		return this.memEnd;
	}

	public void setMemEnd(Date memEnd) {
		this.memEnd = memEnd;
	}

}
