package com.group12.domain.entity;
// Generated Apr 9, 2017 5:30:06 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Parent generated by hbm2java
 */
@Entity
@Table(name = "parent", catalog = "SKF")
public class Parent implements java.io.Serializable {

	private Integer parNum;
	private int stuNum;
	private String parRelation;
	private String parMobileNum;
	private String parEmail;
	private String parFname;
	private String parLname;
	private String parInitial;

	public Parent() {
	}

	public Parent(int stuNum, String parRelation, String parMobileNum, String parEmail, String parFname,
			String parLname) {
		this.stuNum = stuNum;
		this.parRelation = parRelation;
		this.parMobileNum = parMobileNum;
		this.parEmail = parEmail;
		this.parFname = parFname;
		this.parLname = parLname;
	}

	public Parent(int stuNum, String parRelation, String parMobileNum, String parEmail, String parFname,
			String parLname, String parInitial) {
		this.stuNum = stuNum;
		this.parRelation = parRelation;
		this.parMobileNum = parMobileNum;
		this.parEmail = parEmail;
		this.parFname = parFname;
		this.parLname = parLname;
		this.parInitial = parInitial;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Par_Num", unique = true, nullable = false)
	public Integer getParNum() {
		return this.parNum;
	}

	public void setParNum(Integer parNum) {
		this.parNum = parNum;
	}

	@Column(name = "Stu_Num", nullable = false)
	public int getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(int stuNum) {
		this.stuNum = stuNum;
	}

	@Column(name = "Par_Relation", nullable = false, length = 45)
	public String getParRelation() {
		return this.parRelation;
	}

	public void setParRelation(String parRelation) {
		this.parRelation = parRelation;
	}

	@Column(name = "Par_Mobile_Num", nullable = false, length = 45)
	public String getParMobileNum() {
		return this.parMobileNum;
	}

	public void setParMobileNum(String parMobileNum) {
		this.parMobileNum = parMobileNum;
	}

	@Column(name = "Par_Email", nullable = false, length = 45)
	public String getParEmail() {
		return this.parEmail;
	}

	public void setParEmail(String parEmail) {
		this.parEmail = parEmail;
	}

	@Column(name = "Par_FName", nullable = false, length = 45)
	public String getParFname() {
		return this.parFname;
	}

	public void setParFname(String parFname) {
		this.parFname = parFname;
	}

	@Column(name = "Par_LName", nullable = false, length = 45)
	public String getParLname() {
		return this.parLname;
	}

	public void setParLname(String parLname) {
		this.parLname = parLname;
	}

	@Column(name = "Par_Initial", length = 45)
	public String getParInitial() {
		return this.parInitial;
	}

	public void setParInitial(String parInitial) {
		this.parInitial = parInitial;
	}

}
