package com.group12.domain.entity;
// Generated 2017-3-30 17:33:33 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "SKF")
public class User implements java.io.Serializable {

	private String userName;
	private String userPassword;
	private Integer stuNum;

	public User() {
	}

	public User(String userName, String userPassword) {
		this.userName = userName;
		this.userPassword = userPassword;
	}

	public User(String userName, String userPassword, Integer stuNum) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.stuNum = stuNum;
	}

	@Id

	@Column(name = "user_Name", unique = true, nullable = false, length = 30)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_Password", nullable = false, length = 45)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "Stu_Num")
	public Integer getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(Integer stuNum) {
		this.stuNum = stuNum;
	}

}
